apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: khd-file
  description: Retrieve artist details
spec:
  type: file
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
definition:
