apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-portal-analizer-be
  description: backend of api-portal
spec:
  type: service
  lifecycle: production
  owner: cait
  system: PDC000000004
  providesApis:
    - apiportal-analizer-api-v1
  consumesApis:
    - apiportal-api-v1
    - apiportal-api-v2
