apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: deposit-accounts
  description: Deposits Domain
  test: taki-sobie-test
spec:
  owner: deposit-accounts-team

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: current-accounts
  description: Current Domain
spec:
  owner: current-accounts-team

  ---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tools
  description: Tools
spec:
  owner: cait
